'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.KPI
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class language
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.KPI.language", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 業務側受入指摘事項.
        '''</summary>
        Friend Shared ReadOnly Property accepMajor() As String
            Get
                Return ResourceManager.GetString("accepMajor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 登録・閉じる.
        '''</summary>
        Friend Shared ReadOnly Property accept() As String
            Get
                Return ResourceManager.GetString("accept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 住所.
        '''</summary>
        Friend Shared ReadOnly Property address() As String
            Get
                Return ResourceManager.GetString("address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 品質分析表.
        '''</summary>
        Friend Shared ReadOnly Property analysis() As String
            Get
                Return ResourceManager.GetString("analysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指標値 (平均値).
        '''</summary>
        Friend Shared ReadOnly Property average() As String
            Get
                Return ResourceManager.GetString("average", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 生年月日.
        '''</summary>
        Friend Shared ReadOnly Property birthDate() As String
            Get
                Return ResourceManager.GetString("birthDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BRC内部受入.
        '''</summary>
        Friend Shared ReadOnly Property BRCaccept() As String
            Get
                Return ResourceManager.GetString("BRCaccept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 追加.
        '''</summary>
        Friend Shared ReadOnly Property btnAdd() As String
            Get
                Return ResourceManager.GetString("btnAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修のレビューの追加.
        '''</summary>
        Friend Shared ReadOnly Property btnAddError() As String
            Get
                Return ResourceManager.GetString("btnAddError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修の追加.
        '''</summary>
        Friend Shared ReadOnly Property btnAddTask() As String
            Get
                Return ResourceManager.GetString("btnAddTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 戻る.
        '''</summary>
        Friend Shared ReadOnly Property btnBack() As String
            Get
                Return ResourceManager.GetString("btnBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 登録・継続.
        '''</summary>
        Friend Shared ReadOnly Property btnCfmContinue() As String
            Get
                Return ResourceManager.GetString("btnCfmContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 登録・閉じる.
        '''</summary>
        Friend Shared ReadOnly Property btnCfmReturn() As String
            Get
                Return ResourceManager.GetString("btnCfmReturn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 変更.
        '''</summary>
        Friend Shared ReadOnly Property btnChange() As String
            Get
                Return ResourceManager.GetString("btnChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV出力.
        '''</summary>
        Friend Shared ReadOnly Property btnCSV() As String
            Get
                Return ResourceManager.GetString("btnCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 削除.
        '''</summary>
        Friend Shared ReadOnly Property btnDelete() As String
            Get
                Return ResourceManager.GetString("btnDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 詳細.
        '''</summary>
        Friend Shared ReadOnly Property btnDetail() As String
            Get
                Return ResourceManager.GetString("btnDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 編集.
        '''</summary>
        Friend Shared ReadOnly Property btnEdit() As String
            Get
                Return ResourceManager.GetString("btnEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to キャンセル.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to キャプチャの入力が間違っていました。もう一度確認してください。.
        '''</summary>
        Friend Shared ReadOnly Property capchaError() As String
            Get
                Return ResourceManager.GetString("capchaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 品質指標値.
        '''</summary>
        Friend Shared ReadOnly Property cardheaderTarget() As String
            Get
                Return ResourceManager.GetString("cardheaderTarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to プロジェクト.
        '''</summary>
        Friend Shared ReadOnly Property carHeader() As String
            Get
                Return ResourceManager.GetString("carHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to プロジェクトの追加.
        '''</summary>
        Friend Shared ReadOnly Property carHeaderAddProject() As String
            Get
                Return ResourceManager.GetString("carHeaderAddProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to プロジェクトの編集.
        '''</summary>
        Friend Shared ReadOnly Property carHeaderEditProject() As String
            Get
                Return ResourceManager.GetString("carHeaderEditProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 挿入失敗！.
        '''</summary>
        Friend Shared ReadOnly Property ChangeDataFail() As String
            Get
                Return ResourceManager.GetString("ChangeDataFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正常に挿入されました!.
        '''</summary>
        Friend Shared ReadOnly Property ChangeDataSucces() As String
            Get
                Return ResourceManager.GetString("ChangeDataSucces", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードの変更.
        '''</summary>
        Friend Shared ReadOnly Property changePass() As String
            Get
                Return ResourceManager.GetString("changePass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to アクション.
        '''</summary>
        Friend Shared ReadOnly Property clmAction() As String
            Get
                Return ResourceManager.GetString("clmAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指摘・バグ件数.
        '''</summary>
        Friend Shared ReadOnly Property clmBug() As String
            Get
                Return ResourceManager.GetString("clmBug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 作成日.
        '''</summary>
        Friend Shared ReadOnly Property clmCreateAt() As String
            Get
                Return ResourceManager.GetString("clmCreateAt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 部門.
        '''</summary>
        Friend Shared ReadOnly Property clmDP() As String
            Get
                Return ResourceManager.GetString("clmDP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to レビュー指摘事項・バグ分類.
        '''</summary>
        Friend Shared ReadOnly Property clmErrorAnalysis() As String
            Get
                Return ResourceManager.GetString("clmErrorAnalysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 担当者・リーダー.
        '''</summary>
        Friend Shared ReadOnly Property clmLeader() As String
            Get
                Return ResourceManager.GetString("clmLeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 難易度.
        '''</summary>
        Friend Shared ReadOnly Property clmLevel() As String
            Get
                Return ResourceManager.GetString("clmLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to メンバー.
        '''</summary>
        Friend Shared ReadOnly Property clmMember() As String
            Get
                Return ResourceManager.GetString("clmMember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to プロジェクト.
        '''</summary>
        Friend Shared ReadOnly Property clmNP() As String
            Get
                Return ResourceManager.GetString("clmNP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 項番.
        '''</summary>
        Friend Shared ReadOnly Property clmNum() As String
            Get
                Return ResourceManager.GetString("clmNum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to フェーズ.
        '''</summary>
        Friend Shared ReadOnly Property clmPhase() As String
            Get
                Return ResourceManager.GetString("clmPhase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 備考.
        '''</summary>
        Friend Shared ReadOnly Property clmReference() As String
            Get
                Return ResourceManager.GetString("clmReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修内容.
        '''</summary>
        Friend Shared ReadOnly Property clmTask() As String
            Get
                Return ResourceManager.GetString("clmTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修マイン担当.
        '''</summary>
        Friend Shared ReadOnly Property clmUser() As String
            Get
                Return ResourceManager.GetString("clmUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 製造.
        '''</summary>
        Friend Shared ReadOnly Property codePhase() As String
            Get
                Return ResourceManager.GetString("codePhase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 削除プロジェクトを選択してください。.
        '''</summary>
        Friend Shared ReadOnly Property confCkDelete() As String
            Get
                Return ResourceManager.GetString("confCkDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to このプロジェクトを本当に削除しますか？削除後は元に戻すことはできません。.
        '''</summary>
        Friend Shared ReadOnly Property confDelete() As String
            Get
                Return ResourceManager.GetString("confDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to このファイルをダウンロードしますか？.
        '''</summary>
        Friend Shared ReadOnly Property confDownload() As String
            Get
                Return ResourceManager.GetString("confDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 項目.
        '''</summary>
        Friend Shared ReadOnly Property conternt() As String
            Get
                Return ResourceManager.GetString("conternt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV出力.
        '''</summary>
        Friend Shared ReadOnly Property csv() As String
            Get
                Return ResourceManager.GetString("csv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to cdcdfv.
        '''</summary>
        Friend Shared ReadOnly Property demo() As String
            Get
                Return ResourceManager.GetString("demo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 設計.
        '''</summary>
        Friend Shared ReadOnly Property designPhase() As String
            Get
                Return ResourceManager.GetString("designPhase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 詳細.
        '''</summary>
        Friend Shared ReadOnly Property detailContent() As String
            Get
                Return ResourceManager.GetString("detailContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 分析.
        '''</summary>
        Friend Shared ReadOnly Property detailTarget() As String
            Get
                Return ResourceManager.GetString("detailTarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 編集.
        '''</summary>
        Friend Shared ReadOnly Property editQuanlity() As String
            Get
                Return ResourceManager.GetString("editQuanlity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to メールアドレス.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to メールアドレスが存在していません！.
        '''</summary>
        Friend Shared ReadOnly Property emailNotDetail() As String
            Get
                Return ResourceManager.GetString("emailNotDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードを再設定されました。パスワードのリセットメールが送信されました。5分間確認してください。5分後、メールはキャンセルされます。.
        '''</summary>
        Friend Shared ReadOnly Property emaiSendFinish() As String
            Get
                Return ResourceManager.GetString("emaiSendFinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 何もデータが見つかりませんでした！.
        '''</summary>
        Friend Shared ReadOnly Property empData() As String
            Get
                Return ResourceManager.GetString("empData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BRC受入指摘事項.
        '''</summary>
        Friend Shared ReadOnly Property errorAcceptBRC() As String
            Get
                Return ResourceManager.GetString("errorAcceptBRC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OSC様受入指摘事項.
        '''</summary>
        Friend Shared ReadOnly Property errorAcceptOSC() As String
            Get
                Return ResourceManager.GetString("errorAcceptOSC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修内容.
        '''</summary>
        Friend Shared ReadOnly Property errorAnalysis() As String
            Get
                Return ResourceManager.GetString("errorAnalysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新しいエラー分析を作成する.
        '''</summary>
        Friend Shared ReadOnly Property errorHeaderAdd() As String
            Get
                Return ResourceManager.GetString("errorHeaderAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to エラー分析の編集.
        '''</summary>
        Friend Shared ReadOnly Property errorHeaderEdit() As String
            Get
                Return ResourceManager.GetString("errorHeaderEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザーまたはパスワードが間違っているようです。もう一度入力してください。.
        '''</summary>
        Friend Shared ReadOnly Property errorLoginFail() As String
            Get
                Return ResourceManager.GetString("errorLoginFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザーまたはパスワードが3回正しく入力されていません。ユーザーがロックされました。「パスワードをお忘れの方」をクリックしてください。!.
        '''</summary>
        Friend Shared ReadOnly Property errorLoginFailOver() As String
            Get
                Return ResourceManager.GetString("errorLoginFailOver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 入力してください！.
        '''</summary>
        Friend Shared ReadOnly Property errorNullData() As String
            Get
                Return ResourceManager.GetString("errorNullData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to プロジェクトのメンバーを選択してください。!.
        '''</summary>
        Friend Shared ReadOnly Property errorNullMember() As String
            Get
                Return ResourceManager.GetString("errorNullMember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to プロジェク入力してください！.
        '''</summary>
        Friend Shared ReadOnly Property errorNullProject() As String
            Get
                Return ResourceManager.GetString("errorNullProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードは8文字以下で入力してください！.
        '''</summary>
        Friend Shared ReadOnly Property ErrorOverEight() As String
            Get
                Return ResourceManager.GetString("ErrorOverEight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 製造工数に対する指摘率.
        '''</summary>
        Friend Shared ReadOnly Property errorRateOnCode() As String
            Get
                Return ResourceManager.GetString("errorRateOnCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 設計工数に対する指摘率.
        '''</summary>
        Friend Shared ReadOnly Property errorRateOndesign() As String
            Get
                Return ResourceManager.GetString("errorRateOndesign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 設計～テストまでの工数に対する指摘率.
        '''</summary>
        Friend Shared ReadOnly Property errorRateOndesign_test() As String
            Get
                Return ResourceManager.GetString("errorRateOndesign-test", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工数に対する
        '''指摘率.
        '''</summary>
        Friend Shared ReadOnly Property errorRateOnJob() As String
            Get
                Return ResourceManager.GetString("errorRateOnJob", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to テスト時のバグヒット率.
        '''</summary>
        Friend Shared ReadOnly Property errorRateOnTest() As String
            Get
                Return ResourceManager.GetString("errorRateOnTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to レビュー指摘事項.
        '''</summary>
        Friend Shared ReadOnly Property errorReview() As String
            Get
                Return ResourceManager.GetString("errorReview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードをお忘れの方.
        '''</summary>
        Friend Shared ReadOnly Property forGotPassword() As String
            Get
                Return ResourceManager.GetString("forGotPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---プロジェクトのメンバーを選択してください。---.
        '''</summary>
        Friend Shared ReadOnly Property holderMemberSelect() As String
            Get
                Return ResourceManager.GetString("holderMemberSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新パスワードを入力してください....
        '''</summary>
        Friend Shared ReadOnly Property holderNewPass() As String
            Get
                Return ResourceManager.GetString("holderNewPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 現在のパスワードを入力してください....
        '''</summary>
        Friend Shared ReadOnly Property holderOldPass() As String
            Get
                Return ResourceManager.GetString("holderOldPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 確認のため、再度新パスワードを入力してください....
        '''</summary>
        Friend Shared ReadOnly Property holderRetypeNewPass() As String
            Get
                Return ResourceManager.GetString("holderRetypeNewPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ホーム.
        '''</summary>
        Friend Shared ReadOnly Property home() As String
            Get
                Return ResourceManager.GetString("home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザー情報.
        '''</summary>
        Friend Shared ReadOnly Property infouser() As String
            Get
                Return ResourceManager.GetString("infouser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修一覧.
        '''</summary>
        Friend Shared ReadOnly Property listRepair() As String
            Get
                Return ResourceManager.GetString("listRepair", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ログイン.
        '''</summary>
        Friend Shared ReadOnly Property login() As String
            Get
                Return ResourceManager.GetString("login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ログアウト.
        '''</summary>
        Friend Shared ReadOnly Property logout() As String
            Get
                Return ResourceManager.GetString("logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 業務側受入(リリース後含む).
        '''</summary>
        Friend Shared ReadOnly Property majorAccept() As String
            Get
                Return ResourceManager.GetString("majorAccept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指標.
        '''</summary>
        Friend Shared ReadOnly Property menu() As String
            Get
                Return ResourceManager.GetString("menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新パスワード.
        '''</summary>
        Friend Shared ReadOnly Property newPass() As String
            Get
                Return ResourceManager.GetString("newPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ～入力してください！.
        '''</summary>
        Friend Shared ReadOnly Property noData() As String
            Get
                Return ResourceManager.GetString("noData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザーIDを入力することが必要！.
        '''</summary>
        Friend Shared ReadOnly Property noDataID() As String
            Get
                Return ResourceManager.GetString("noDataID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードを入力することが必要！.
        '''</summary>
        Friend Shared ReadOnly Property noDatapass() As String
            Get
                Return ResourceManager.GetString("noDatapass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to あなたのためのプロジェクトはありません.
        '''</summary>
        Friend Shared ReadOnly Property noProject() As String
            Get
                Return ResourceManager.GetString("noProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 電話番号.
        '''</summary>
        Friend Shared ReadOnly Property numberPhane() As String
            Get
                Return ResourceManager.GetString("numberPhane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to バグ件数.
        '''</summary>
        Friend Shared ReadOnly Property numBug() As String
            Get
                Return ResourceManager.GetString("numBug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工数.
        '''</summary>
        Friend Shared ReadOnly Property numJob() As String
            Get
                Return ResourceManager.GetString("numJob", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工数
        '''（設計～テスト）.
        '''</summary>
        Friend Shared ReadOnly Property numJobDesignText() As String
            Get
                Return ResourceManager.GetString("numJobDesignText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to テスト件数.
        '''</summary>
        Friend Shared ReadOnly Property numTest() As String
            Get
                Return ResourceManager.GetString("numTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 現在のパスワード.
        '''</summary>
        Friend Shared ReadOnly Property oldPass() As String
            Get
                Return ResourceManager.GetString("oldPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OSC様受入.
        '''</summary>
        Friend Shared ReadOnly Property OSCaccept() As String
            Get
                Return ResourceManager.GetString("OSCaccept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 違うパスワード.
        '''</summary>
        Friend Shared ReadOnly Property passANotdetail() As String
            Get
                Return ResourceManager.GetString("passANotdetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードが確認用パスワードと一致していません.
        '''</summary>
        Friend Shared ReadOnly Property passDiffrent() As String
            Get
                Return ResourceManager.GetString("passDiffrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワード.
        '''</summary>
        Friend Shared ReadOnly Property passWord() As String
            Get
                Return ResourceManager.GetString("passWord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to フェーズ.
        '''</summary>
        Friend Shared ReadOnly Property phase() As String
            Get
                Return ResourceManager.GetString("phase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --指摘・バグ件数を入力してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdBug() As String
            Get
                Return ResourceManager.GetString("phdBug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --フェーズを選択してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdError() As String
            Get
                Return ResourceManager.GetString("phdError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --レベルを選択してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdLevel() As String
            Get
                Return ResourceManager.GetString("phdLevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --フェーズを選択してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdPhase() As String
            Get
                Return ResourceManager.GetString("phdPhase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --備考を入力してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdReference() As String
            Get
                Return ResourceManager.GetString("phdReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --改修内容を入力してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdTask() As String
            Get
                Return ResourceManager.GetString("phdTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --改修を選択してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdTaskk() As String
            Get
                Return ResourceManager.GetString("phdTaskk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --改修メイン担当を選択してください--.
        '''</summary>
        Friend Shared ReadOnly Property phdUser() As String
            Get
                Return ResourceManager.GetString("phdUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to バグヒット率.
        '''</summary>
        Friend Shared ReadOnly Property rateBugHit() As String
            Get
                Return ResourceManager.GetString("rateBugHit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ★あり：問題の原因分析、改善方針等々&lt;/br&gt;
        '''★なし：成功の原因分析、波及方法等々.
        '''</summary>
        Friend Shared ReadOnly Property reason() As String
            Get
                Return ResourceManager.GetString("reason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ★あり：問題の原因分析、改善方針等
        '''★なし：成功の原因分析、波及方法等々.
        '''</summary>
        Friend Shared ReadOnly Property reasonCSV() As String
            Get
                Return ResourceManager.GetString("reasonCSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新パスワード（確認用).
        '''</summary>
        Friend Shared ReadOnly Property retypeNewPass() As String
            Get
                Return ResourceManager.GetString("retypeNewPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワード （確認用).
        '''</summary>
        Friend Shared ReadOnly Property retypePassword() As String
            Get
                Return ResourceManager.GetString("retypePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 検索....
        '''</summary>
        Friend Shared ReadOnly Property search() As String
            Get
                Return ResourceManager.GetString("search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 送信.
        '''</summary>
        Friend Shared ReadOnly Property send() As String
            Get
                Return ResourceManager.GetString("send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to パスワードを再設定.
        '''</summary>
        Friend Shared ReadOnly Property setPassword() As String
            Get
                Return ResourceManager.GetString("setPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 品質指標.
        '''</summary>
        Friend Shared ReadOnly Property target() As String
            Get
                Return ResourceManager.GetString("target", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工数(製造).
        '''</summary>
        Friend Shared ReadOnly Property targetCode() As String
            Get
                Return ResourceManager.GetString("targetCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 工数(設計).
        '''</summary>
        Friend Shared ReadOnly Property targetDesign() As String
            Get
                Return ResourceManager.GetString("targetDesign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to テスト件数(テスト).
        '''</summary>
        Friend Shared ReadOnly Property targetTest() As String
            Get
                Return ResourceManager.GetString("targetTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修一覧.
        '''</summary>
        Friend Shared ReadOnly Property taskHeader() As String
            Get
                Return ResourceManager.GetString("taskHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修の追加.
        '''</summary>
        Friend Shared ReadOnly Property taskHeaderAdd() As String
            Get
                Return ResourceManager.GetString("taskHeaderAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 改修の編集.
        '''</summary>
        Friend Shared ReadOnly Property taskHeaderEdit() As String
            Get
                Return ResourceManager.GetString("taskHeaderEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to テスト.
        '''</summary>
        Friend Shared ReadOnly Property testPhase() As String
            Get
                Return ResourceManager.GetString("testPhase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to レビュー指摘事項・バグ分類及び分析表.
        '''</summary>
        Friend Shared ReadOnly Property titleErrorAnalysis() As String
            Get
                Return ResourceManager.GetString("titleErrorAnalysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 指標値 （許容範囲）.
        '''</summary>
        Friend Shared ReadOnly Property tolerance() As String
            Get
                Return ResourceManager.GetString("tolerance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザー名.
        '''</summary>
        Friend Shared ReadOnly Property usename() As String
            Get
                Return ResourceManager.GetString("usename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ユーザー情報.
        '''</summary>
        Friend Shared ReadOnly Property userInfo() As String
            Get
                Return ResourceManager.GetString("userInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 基準値
        '''超過有無.
        '''</summary>
        Friend Shared ReadOnly Property yesNoOverStand() As String
            Get
                Return ResourceManager.GetString("yesNoOverStand", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
